"""added expenses tables and relation to trips table

Revision ID: a694e5ed1eca
Revises: 6f7f395feab9
Create Date: 2025-10-13 16:21:26.755226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a694e5ed1eca'
down_revision: Union[str, Sequence[str], None] = '6f7f395feab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
